---
title: "Lower Limb Prosthetic Gait Analysis"
author: "Cora Ferguson"
date: "2022-11-19"
output: html_document
---

# Introduction
In the United States alone, approximately 1.9 million individuals in the United States are living with lower limb loss [1].  Lower limb loss is characterized by amputation below the knee.  A variety of different conditions contribute to lower limb loss including traumatic injuries, diabetes, peripheral artery disease, and more.  With the rise in the prevalence of these diseases, the number of individuals facing lower limb loss is unfortunately projected to go up. To meet the increasing demand for prosthetic devices, new technology is being developed with the goal of balancing cost, functionality, and comfort for these patients - both short term and long term.  

Extended prosthetic use 

Current prosthetic devices are categorized as active or passive. lower limb prosthetic devices are there are two main types of lower leg prosthetic devices available on the market - active prostheses and passive prostheses. Active prosthetic devices have a microprocessor that is incorporated into the ankle joint.  This serves to adjust the angle of the foot of the prosthetic before the user touches the ground – mimicking the natural motion of the ankle [2].  The goal of this small adjustment is to limit the strain on the rest of the body by mimicking the natural motion of the ankle - thus reducing the amount of force needed to compensate while moving the prosthetic device. Active prostheses are typically more expensive and require additional maintenance such as charging but have been shown to alleviate some additional strain associated with prosthetic compensation [2].

Passive prostheses are the other class of prosthetic devices that do not contain a microprocessor.  As such, they do not require charging or as much maintenance but they are less adjustable to the individual's biomechanics. 


This data set collects information from a number of different sI am looking at focuses on the biomechanics of a prosthetic leg with a microprocessor computer in it and an passive prosthetic leg without one.   With this in mind, I hope to explore the relationship between prosthetic type – active (with microcontroller) vs passive (without microcontroller).  
# Analysis

# Biological Summary

# Challenges

# References
[1] Balk EM, Gazula A, Markozannes G, et al. Lower Limb Prostheses: Measurement Instruments, Comparison of Component Effects by Subgroups, and Long-Term Outcomes [Internet]. Rockville (MD): Agency for Healthcare Research and Quality (US); 2018 Sep. (Comparative Effectiveness Review, No. 213.) Evidence Summary. Available from: https://www.ncbi.nlm.nih.gov/books/NBK531527/

[2] Childers, W. L., & Takahashi, K. Z. (2018). Increasing prosthetic foot energy return affects whole-body mechanics during walking on level ground and slopes. Scientific Reports 2018 8:1, 8(1), 1–12. https://doi.org/10.1038/s41598-018-23705-8